# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flowbear < Formula
  desc "The Anti-Ghostwriter - Privacy-first writing assistant"
  homepage "https://github.com/scttfrdmn/flowbear"
  version "0.3.0"
  license "Proprietary"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/scttfrdmn/flowbear/releases/download/v0.3.0/flowbear-0.3.0-darwin-amd64.tar.gz"
    sha256 "7df39c3950e9d7880af432d48d01a24a3a4c2996320fd84621f49531a872d949"

    def install
      bin.install "flowbear"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/scttfrdmn/flowbear/releases/download/v0.3.0/flowbear-0.3.0-darwin-arm64.tar.gz"
    sha256 "29b0a3d0e8ffe23105ecfbc6519f12db52e7018e7d6a7991e901dedb1d6e2ec0"

    def install
      bin.install "flowbear"
    end
  end

  test do
    system "#{bin}/flowbear", "version"
  end
end
